import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { createGame, createMonster, ITEM_PRICES, speciesAbilities } from '../../src/game/engine';
import { defaultView, packSave } from '../../src/game/storage';
import type { Graph } from '../../src/core/brain';

const graph = JSON.parse(readFileSync('public/data/connectome.json', 'utf8')) as Graph;
test.use({ channel: 'chrome', headless: false, launchOptions: { args: ['--enable-unsafe-webgpu'] } });
test('search, bulk merge, automatic merge setting and assignment persist on mobile', async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/auth/me', route => route.fulfill({ json: { user: null } }));
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.route(/\.(?:glb|gltf)(?:\?.*)?$/, route => route.abort());
  const game = createGame(1, 'streamlined-box'), survivor = game.player.team[0];
  game.inventory.leftovers = 1;
  game.player.box = Array.from({ length: 105 }, (_, index) => createMonster(game, index % 2 ? 25 : 1, 5 + index % 15));
  await page.goto('/');
  await page.locator('[data-starter="152"]').click();
  await page.locator('#import-file').setInputFiles({ name: 'box.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorldPaused: true }))) });
  await expect(page.locator('#toast')).toContainText('불러왔습니다');
  await page.locator('[data-tab="team"]').click();
  await expect(page.locator('.collection-actions')).not.toContainText('기준선');
  await page.locator('#box-search').fill('PIKACHU 전기');
  await expect(page.locator('.box-result-line')).toContainText('52마리');
  await page.locator('#box-more').scrollIntoViewIfNeeded();
  await expect(page.locator('.box-monster')).toHaveCount(52);
  await page.locator('.box-monster').first().click();
  await expect(page.locator('.detail-navigator')).toContainText('1 / 52');
  await page.getByRole('button', { name: '다음 포켓몬', exact: true }).click();
  await expect(page.locator('.detail-navigator')).toContainText('2 / 52');
  await page.locator('#box-clear').click();
  await page.locator(`[data-monster="${survivor.instanceId}"]`).click();
  await page.locator('#monster-tool').selectOption('leftovers');
  const alternative = speciesAbilities(1).find(ability => ability.slot !== survivor.ability!.slot)!;
  await page.locator('#monster-ability').selectOption(String(alternative.slot));
  await page.locator('#open-interface-settings').click();
  await page.locator('#collection-auto-merge').check();
  await expect(page.locator('#collection-auto-merge')).toBeEnabled();
  await page.locator('.settings-close').click();
  await page.locator('#merge-collection').click();
  const dialog = page.getByRole('dialog', { name: '중복 한번에 합치기' });
  await expect(dialog).toContainText('104마리');
  await dialog.getByRole('button', { name: '합치기', exact: true }).click();
  await expect(page.locator('.count-chip')).toContainText('박스 1');
  await expect(page.locator('#monster-tool')).toHaveValue('leftovers');
  await expect(page.locator('#monster-ability')).toHaveValue(String(alternative.slot));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('collection-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#save-now').click();
  await expect(page.locator('#save-state')).toContainText('저장됨');
  await page.reload();
  await page.locator('[data-tab="team"]').click();
  await expect(page.locator('.count-chip')).toContainText('박스 1');
  await expect(page.locator('#monster-tool')).toHaveValue('leftovers');
  await page.locator('#open-interface-settings').click();
  await expect(page.locator('#collection-auto-merge')).toBeChecked();
  expect(errors).toEqual([]);
});

test('evolution buys only the missing item and removes the shop from the exploration panel', async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/auth/me', route => route.fulfill({ json: { user: null } }));
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.route(/\.(?:glb|gltf)(?:\?.*)?$/, route => route.abort());
  const game = createGame(1, 'evolution-purchase-ui'), onix = createMonster(game, 95, 30);
  game.player.box = [onix]; game.player.money = ITEM_PRICES['metal-coat'];
  await page.goto('/'); await page.locator('[data-starter="152"]').click();
  await page.locator('#import-file').setInputFiles({ name: 'evolution.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorldPaused: true }))) });
  await expect(page.locator('#toast')).toContainText('불러왔습니다');
  await expect(page.locator('.world-shop')).toHaveCount(0);
  await expect(page.locator('.adventure-loading')).toHaveCount(0);
  await page.locator('[data-tab="team"]').click();
  await page.locator(`[data-monster="${onix.instanceId}"]`).click();
  await page.locator('.evolution-panel > summary').click();
  await page.locator('[data-evolve="208"][data-evolution-item="metal-coat"]').click();
  await expect(page.locator('.detail-title h2')).toHaveText('강철톤');
  await expect(page.locator('#money')).toContainText('0');
  await page.screenshot({ path: testInfo.outputPath('evolution-purchased.png'), fullPage: true });
});

test('Alola appearance and Mega or Tera battle controls use persistent game state', async ({ page }) => {
  test.setTimeout(90_000);
  await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/auth/me', route => route.fulfill({ json: { user: null } }));
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.route(/\.(?:glb|gltf)(?:\?.*)?$/, route => route.abort());
  const game = createGame(4, 'forms-ui'), charizard = createMonster(game, 6, 50), raichu = createMonster(game, 26, 30), enemy = createMonster(game, 7, 50);
  game.player.team = [charizard]; game.player.box = [raichu];
  const load = async () => {
    await page.locator('#import-file').setInputFiles({ name: 'forms.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorldPaused: true }))) });
    await expect(page.locator('#toast')).toContainText('불러왔습니다');
  };
  await page.goto('/'); await page.locator('[data-starter="152"]').click(); await load();
  await page.locator('[data-tab="team"]').click();
  await page.locator(`[data-monster="${raichu.instanceId}"]`).click();
  await page.locator('#monster-form').selectOption('alola');
  await expect(page.locator('.detail-title .type-psychic')).toBeVisible();
  await expect(page.locator('.detail-portrait img')).toHaveAttribute('src', /10100\.png$/);
  await page.locator('#box-search').fill('알로라 에스퍼');
  await expect(page.locator('.box-monster')).toHaveCount(1);
  game.battle = { kind: 'wild', regionId: game.regionId, player: { team: game.player.team, activeIndex: 0 }, enemy: { team: [enemy], activeIndex: 0 }, turn: 1, canRun: true };
  await load(); await page.locator('[data-tab="map"]').click();
  await page.locator('[data-mega-form]').selectOption('charizard-mega-x');
  await page.locator('[data-battle-transformation="mega"]').click();
  await expect(page.locator('[data-transformation-active="mega"]')).toBeVisible();
  await expect(page.locator('.player.combatant .type-dragon')).toBeVisible();
  await expect(page.locator('.player.combatant img')).toHaveAttribute('src', /10034\.png$/);
  await load();
  await page.locator('[data-tera-type]').selectOption('water');
  await page.locator('[data-battle-transformation="tera"]').click();
  await expect(page.locator('[data-transformation-active="tera"]')).toHaveText('물 테라스탈');
  await expect(page.locator('.player.combatant .type-water')).toBeVisible();
  await page.locator('#save-now').click();
  await expect(page.locator('#save-state')).toContainText('저장됨');
  await page.reload();
  await expect(page.locator('[data-transformation-active="tera"]')).toHaveText('물 테라스탈');
});
