import { mockAuthenticatedSession } from './helpers/authenticated-session';
import { expect, test } from '@playwright/test';
import { mkdirSync, readFileSync } from 'node:fs';
import { createGame, createMonster, ITEM_PRICES } from '../../src/game/engine';
import { ConnectomeController } from '../../src/game/connectome';
import { EXTRA_EVOLUTION_ITEM_IDS } from '../../src/game/evolution-items';
import { defaultView, packSave } from '../../src/game/storage';
import { clickAccountMenu } from './helpers/account-menu';

test('auto-buys a missing Metal Coat from evolution and keeps regular shop purchases', async ({ page }) => {
  test.setTimeout(150_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await mockAuthenticatedSession(page);
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  const graph = JSON.parse(readFileSync('public/data/connectome.json', 'utf8'));
  const game = createGame(152, 'evolution-shop-ui'), onix = createMonster(game, 95, 25), scyther = createMonster(game, 123, 25);
  game.player.team = [onix]; game.player.box = [scyther]; game.player.money = 20_000;
  game.dex.caught = [95,123,152]; game.dex.seen = [...game.dex.caught];
  const controller = new ConnectomeController(graph); controller.ensure(onix); controller.ensure(scyther);
  const save = JSON.parse(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorldPaused: true, learning: false })));
  for (const item of EXTRA_EVOLUTION_ITEM_IDS) delete save.game.inventory[item];
  await page.goto('/'); await page.locator('[data-starter="1"]').click();
  await page.locator('#import-file').setInputFiles({ name: 'legacy-tools.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(save)) });
  await expect(page.locator('#toast')).toContainText('불러왔습니다');
  await expect(page.locator('.world-shop')).toHaveCount(0);

  await page.locator('[data-tab="team"]').click();
  await page.locator('.evolution-panel > summary').click();
  const onixEvolution = page.locator('[data-evolve="208"][data-evolution-item="metal-coat"]');
  await expect(onixEvolution).toContainText('금속코트 ×1 · 보유 0개');
  await expect(onixEvolution).toContainText(`자동 구매 ₩${ITEM_PRICES['metal-coat'].toLocaleString('ko-KR')}`);
  await expect(onixEvolution).toContainText('구매 후 진화');
  await onixEvolution.click();
  await expect(page.locator('.detail-title h2')).toHaveText('강철톤');
  await expect(page.locator('#money')).toContainText('16,000');
  await expect(page.locator('#pokemon-canvas')).toHaveAttribute('data-species', '208', { timeout: 45_000 });
  await expect(page.locator('#pokemon-canvas')).toHaveAttribute('data-ready', 'true');

  await page.locator('[data-tab="shop"]').click();
  const card = page.locator('.shop-card').filter({ has: page.locator('[data-buy="metal-coat"]') });
  await expect(card).toContainText('롱스톤 → 강철톤'); await expect(card).toContainText('스라크 → 핫삼');
  await page.locator('[data-buy="metal-coat"]').click(); await expect(card).toContainText('보유 1개');
  mkdirSync('artifacts/evolution-shop', { recursive: true });
  await card.screenshot({ path: 'artifacts/evolution-shop/metal-coat.png' });
  await page.locator('[data-tab="team"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(`[data-monster="${scyther.instanceId}"]`).click();
  await page.locator('.evolution-panel > summary').click();
  const scytherEvolution = page.locator('[data-evolve="212"][data-evolution-item="metal-coat"]');
  await expect(scytherEvolution).toContainText('금속코트 ×1 · 보유 1개');
  await expect(scytherEvolution).toContainText('준비 완료');
  await scytherEvolution.click();
  await expect(page.locator('.detail-title h2')).toHaveText('핫삼');
  await expect(page.locator('#pokemon-canvas')).toHaveAttribute('data-species', '212', { timeout: 45_000 });
  await expect(page.locator('#pokemon-canvas')).toHaveAttribute('data-ready', 'true');
  await page.locator('.detail-title').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/evolution-shop/scizor-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.setViewportSize({ width: 1440, height: 1100 });
  await clickAccountMenu(page, '#save-now'); await expect(page.locator('#save-state')).toContainText('저장됨');
  await page.reload();
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 45_000 });
  await page.locator('[data-tab="team"]').click();
  await expect(page.locator(`.monster-card[data-monster="${onix.instanceId}"]`)).toContainText('강철톤');
  await expect(page.locator(`.monster-card[data-monster="${scyther.instanceId}"]`)).toContainText('핫삼');
  await page.locator('[data-tab="shop"]').click();
  await expect(page.locator('.shop-card').filter({ has: page.locator('[data-buy="metal-coat"]') })).toContainText('보유 0개');
  await expect(page.locator('.wallet')).toHaveText('₩12,000');
  expect(errors).toEqual([]);
});
