import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import type { Graph } from '../../src/core/brain';
import { createGame, createMonster, HELD_TOOL_DESCRIPTIONS, type HeldTool } from '../../src/game/engine';
import { getFieldItemSources } from '../../src/openworld/item-sources';
import { defaultView, packSave } from '../../src/game/storage';
import { OpenWorldSimulation } from '../../src/openworld/simulation';
import { mockAuthenticatedSession } from './helpers/authenticated-session';
import { buildExplorationSites } from '../../src/openworld/exploration-sites';

const graph = JSON.parse(readFileSync('public/data/connectome.json', 'utf8')) as Graph;
test('roadside items render in 3D, collect once, persist and show acquisition sources on the searchable map', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const game = createGame(1, 'roadside-ui'), world = new OpenWorldSimulation(graph, game, 517);
  world.setControlMode('manual'); world.setAutoHunt(false);
  const item = world.fieldPickups.find(item => item.kind === 'held-tool')!;
  expect(item).toBeDefined();
  const arrival = world.atlas.nearestWalkable(item.x + 1.4, item.z, 0)!;
  world.player = { ...arrival, heading: 0 }; Object.assign(world.entities.find(entity => entity.kind === 'companion')!, world.player);
  await mockAuthenticatedSession(page); await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.goto('/?renderProbe'); await page.locator('[data-starter="152"]').click();
  await page.locator('#import-file').setInputFiles({ name: 'roadside.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorld: world.snapshot(), openWorldPaused: true }))) });
  await expect(page.locator('#toast')).toContainText('불러왔습니다');
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 45_000 });
  const pickup = page.locator(`[data-field-pickup="${item.id}"]`);
  await expect(pickup).toContainText('줍기');
  await expect.poll(() => page.evaluate(id => (window as any).__renderProbe.read().fieldItems.some((item: any) => item.itemId === id && item.drawn > 0), item.itemId), { timeout: 20000 }).toBe(true);
  await page.screenshot({ path: info.outputPath('roadside-pickup.png'), fullPage: true });
  await pickup.click(); await expect(page.locator('#toast')).toContainText(`${item.name} +1`); await expect(pickup).toHaveCount(0);
  await page.locator('#save-now').click(); await expect(page.locator('#save-state')).toContainText('저장됨');
  await page.reload(); await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 45_000 });
  await expect(pickup).toHaveCount(0);
  await page.locator('[data-tab="team"]').click();
  await expect(page.locator('#monster-transformation option[value^="tera:"]')).toHaveCount(0);
  await expect(page.locator(`#monster-tool option[value="${item.itemId}"]`)).toHaveJSProperty('disabled', false);
  await expect(page.locator('#monster-tool optgroup')).toHaveCount(3);
  expect(await page.locator('#monster-tool optgroup').evaluateAll(groups => groups.map(group => group.getAttribute('label')))).toEqual(['장착 도구', '열매', '보조']);
  await page.locator('#monster-tool').selectOption(item.itemId);
  await expect(page.locator('#monster-tool')).toHaveValue(item.itemId);
  await expect(page.locator('#monster-tool-description')).toHaveText(HELD_TOOL_DESCRIPTIONS[item.itemId as HeldTool]);
  await page.locator('#monster-tool').scrollIntoViewIfNeeded(); await page.screenshot({ path: info.outputPath('team-tool.png') });
  await page.locator('.item-source-guide > summary').click();
  await page.locator(`[data-item-source="${item.itemId}"] > summary`).click();
  const chance = getFieldItemSources(item.itemId)!.captures[0].chance;
  await expect(page.locator(`[data-item-source="${item.itemId}"]`)).toContainText(`${Number((chance * 100).toFixed(2))}%`);
  await expect(page.locator(`[data-item-source="${item.itemId}"]`)).toContainText('길가에서 줍기');
  await page.locator('[data-tab="map"]').click(); await page.locator('#world-map-open').click();
  await expect(page.locator('#world-map-content svg image')).toHaveAttribute('href', /^blob:/);
  await page.locator('#world-map-search').fill(item.name);
  const results = page.locator('[data-map-list-location]'); expect(await results.count()).toBeGreaterThan(0);
  await results.first().click(); await expect(page.locator('.map-location-detail')).toContainText(item.name);
  await expect(page.locator('.map-item-sources')).toContainText('길가에서 줍기');
  await page.locator('#world-map-search').fill('없는도구123'); await expect(results).toHaveCount(0);
  await page.locator('#world-map-search').fill(''); await page.locator('#world-map-filter').selectOption('town');
  expect(await results.count()).toBeGreaterThan(0);
  await page.screenshot({ path: info.outputPath('map-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('map-mobile.png'), fullPage: true });
  await page.locator('#world-map-close').click(); await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#world-resume').click(); await page.locator('#world-map-open').click();
  await page.locator('#world-map-filter').selectOption('all');
  await page.locator('#world-map-search').fill(world.atlas.locationAt(arrival.x, arrival.z).name);
  await page.locator(`[data-map-list-location="${world.atlas.locationAt(arrival.x, arrival.z).id}"]`).click();
  const before = await page.evaluate(() => (window as any).__renderProbe.read().streaming.player);
  await page.locator('#world-map-go').click(); await expect(page.locator('#world-map-dialog')).not.toBeVisible();
  await expect.poll(() => page.evaluate(before => { const player = (window as any).__renderProbe.read().streaming.player; return Math.hypot(player.x - before.x, player.z - before.z); }, before), { timeout: 10000 }).toBeGreaterThan(.5);
  expect(errors).toEqual([]);
});

for (const [region, starter] of [['johto', 152], ['alola', 722], ['sinnoh', 387]] as const) test(`regional exploration landmarks render beside a traversable road (${region})`, async ({ page }, info) => {
  const game = createGame(152, 'exploration-sites-ui');
  if (region !== 'johto') {
    game.player.badges = 8; game.defeatedGyms = [1,2,3,4,5,6,7,8]; game.championDefeated = true;
    game.campaign!.johtoBadges = [1,2,3,4,5,6,7,8]; game.campaign!.johtoLeague = 5; game.campaign!.kantoLeague = 5;
    const sequence = ['hoenn', 'sinnoh', 'unova', 'kalos', 'alola'] as const;
    game.campaign!.expansion = Object.fromEntries(sequence.slice(0, sequence.indexOf(region)).map(id => [id, { badges: [1,2,3,4,5,6,7,8], league: 5 }]));
    game.claimedRegionalStarters = ['kanto', 'johto', ...sequence];
    game.player.team = [createMonster(game, starter, 15, region)]; game.dex.seen = [152, starter]; game.dex.caught = [152, starter];
  }
  const world = new OpenWorldSimulation(graph, game, 739);
  if (region !== 'johto') world.changeRegion(region);
  world.setControlMode('manual'); world.setAutoHunt(false);
  const site = buildExplorationSites(world.atlas, world.atlas.sample, 0).find(site => site.kind === 'rest' || site.kind === 'junction')!;
  expect(site).toBeDefined();
  const arrival = [{ x: site.x + 1, z: site.z - 2 }, { x: site.x - 1, z: site.z - 2 }, { x: site.x, z: site.z }]
    .find(point => world.atlas.evaluateTraversal(point, point, 0).allowed)!;
  expect(Math.hypot(arrival.x - site.x, arrival.z - site.z)).toBeLessThan(3);
  world.player = { ...arrival, heading: 0 }; Object.assign(world.entities.find(entity => entity.kind === 'companion')!, world.player);
  await mockAuthenticatedSession(page); await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.goto('/?renderProbe'); await page.locator('[data-starter="152"]').click();
  await page.locator('#import-file').setInputFiles({ name: 'exploration.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packSave(game, graph, { ...defaultView(), openWorld: world.snapshot(), openWorldPaused: true }))) });
  await expect(page.locator('#ow-host')).toHaveAttribute('data-region', region);
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 45_000 });
  await expect.poll(() => page.evaluate(id => (window as any).__renderProbe.read().explorationSites.some((site: any) => site.id === id), site.id), { timeout: 20000 }).toBe(true);
  await page.screenshot({ path: info.outputPath('exploration-landmarks.png'), fullPage: true });
});
