import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { openExplorePanel } from './helpers/explore-panel';

test('nameplates are opt-in and selection stays at bottom left on desktop and mobile', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [], failed: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400) failed.push(response.url()); });
  await page.goto(process.env.KANTO_URL ? `${process.env.KANTO_URL}?renderProbe` : '/?renderProbe');
  await page.locator('[data-starter="152"]').click();
  await openExplorePanel(page);
  await page.locator('#world-mode-manual').click();
  await page.locator('#world-auto-hunt').uncheck();
  await page.locator('#world-pause').click();
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 30000 });
  const labels = page.locator('#world-nameplates');
  await expect(labels).toHaveAttribute('aria-pressed', 'false');
  await expect.poll(() => page.evaluate(() => (window as any).__renderProbe?.read().nameplates)).toBe(0);
  await labels.click();
  await expect(labels).toHaveAttribute('aria-pressed', 'true');
  await expect.poll(() => page.evaluate(() => (window as any).__renderProbe.read().nameplates)).toBeGreaterThan(0);
  await labels.click();
  await expect.poll(() => page.evaluate(() => (window as any).__renderProbe.read().nameplates)).toBe(0);
  await page.locator('.world-objective summary').click();
  await page.locator('[data-world-wild]').first().click();
  const target = page.locator('#world-target');
  await expect(target).toBeVisible();
  await expect(target).toContainText('HP');
  const desktop = (await target.boundingBox())!;
  expect(desktop.x).toBeLessThan(40); expect(desktop.y).toBeGreaterThan(800); expect(desktop.height).toBeLessThan(110);
  const partner = page.locator('.world-battle-hud');
  expect((await partner.boundingBox())!.x).toBeGreaterThan(desktop.x + desktop.width);
  expect((await page.locator('.topbar').boundingBox())!.height).toBeLessThanOrEqual(54);
  await page.locator('#world-target-track').click();
  await expect(page.locator('#world-mode-auto')).toHaveAttribute('aria-pressed', 'true');
  await expect.poll(() => page.evaluate(() => (window as any).__renderProbe.read().nameplates)).toBe(0);
  await mkdir('artifacts/render-upgrade', { recursive: true });
  await page.screenshot({ path: 'artifacts/render-upgrade/selection.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(target).toBeVisible();
  expect((await target.boundingBox())!.x).toBeLessThan(20);
  const mobileTarget = (await target.boundingBox())!, mobilePartner = (await partner.boundingBox())!;
  expect(mobilePartner.y + mobilePartner.height).toBeLessThanOrEqual(mobileTarget.y);
  expect(mobileTarget.y).toBeGreaterThan(844 * .75);
  expect((await page.locator('.topbar').boundingBox())!.height).toBeLessThanOrEqual(82);
  await page.screenshot({ path: 'artifacts/render-upgrade/mobile-selection.png' });
  await expect(page.locator('.world-battle-hud')).not.toHaveAttribute('open', '');
  expect(Math.abs((await target.boundingBox())!.y - mobileTarget.y)).toBeLessThan(1);
  expect((await partner.boundingBox())!.x).toBeGreaterThanOrEqual(mobileTarget.x + mobileTarget.width);
  await page.screenshot({ path: 'artifacts/render-upgrade/mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await expect(page.locator('#world-nameplates')).toHaveAttribute('aria-pressed', 'false', { timeout: 30000 });
  expect(errors).toEqual([]);
  expect(failed).toEqual([]);
});
