import { expect, test } from '@playwright/test';
import { openExplorePanel } from './helpers/explore-panel';
import { readFileSync } from 'node:fs';
import { createGame } from '../../src/game/engine';
import { defaultView, packSave } from '../../src/game/storage';
import { OpenWorldSimulation } from '../../src/openworld/simulation';

test.use({ launchOptions: { args: ['--mute-audio', '--enable-unsafe-webgpu'] } });
test('the local trainer menu starts an ordinary battle and saves it', async ({ page }) => {
  test.setTimeout(90_000);
  await page.routeWebSocket('**', socket => socket.close());
  await page.route('**/api/auth/me', route => route.fulfill({ json: { user: null } }));
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.route(/\.(?:glb|gltf)(?:\?.*)?$/, route => route.abort());
  await page.goto('/');
  await page.locator('[data-starter="1"]').click();
  const graph = JSON.parse(readFileSync('public/data/connectome.json', 'utf8'));
  const policy = JSON.parse(readFileSync('public/data/openworld-policy.json', 'utf8'));
  const game = createGame(152, 'trainer-menu-ui');
  const world = new OpenWorldSimulation(graph, game, 91234, undefined, policy);
  const save = packSave(game, graph, { ...defaultView(), openWorld: world.snapshot(), openWorldPaused: true, learning: false });
  await page.locator('#import-file').setInputFiles({ name: 'trainer-menu.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(save)) });
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 30_000 });
  await openExplorePanel(page);
  await page.locator('#world-trainer-open').click();
  await expect(page.locator('#world-trainer-dialog')).toBeVisible();
  await expect(page.locator('#world-trainer-description')).toContainText('연두');
  await page.locator('[data-trainer-battle="practice-johto-new-bark"]').click();
  await page.locator('#world-pause').click();
  await expect(page.locator('#world-pause')).toBeEnabled();
  await expect(page.locator('#world-trainer-dialog')).not.toBeVisible();
  await expect(page.locator('#world-feed')).toContainText('트레이너 배틀을 신청');
  await expect(page.locator('#world-run')).toBeDisabled();
  await expect(page.locator('#world-trainer-open')).toBeDisabled();
  await page.screenshot({ path: 'artifacts/trainer-menu-ui/battle.png' });
  await page.reload();
  await expect(page.locator('#ow-host')).toHaveAttribute('data-ready', 'true', { timeout: 30_000 });
  await openExplorePanel(page);
  await expect(page.locator('#world-trainer-open')).toBeDisabled();
  await expect(page.locator('#world-feed')).toContainText('트레이너 배틀을 신청');
  await expect(page.locator('#world-run')).toBeDisabled();
});
