import { expect, test } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createGame, createMonster } from '../../src/game/engine';
import { defaultView, packSave } from '../../src/game/storage';
import { OpenWorldSimulation } from '../../src/openworld/simulation';
import { getWorldAtlas } from '../../src/openworld/atlas';
import type { Graph } from '../../src/core/brain';

test('streams real generation 2 models, travels between maps and restores the selected region', async ({ page }) => {
  test.setTimeout(150000);
  const errors: string[] = [], modelRequests = new Set<string>();
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (/Pokemon-3D-api.*\.glb/.test(request.url())) modelRequests.add(request.url()); });
  await page.route('**/api/auth/me', route => route.fulfill({ json: { user: null } }));
  await page.route('**/api/connectome', route => route.fulfill({ json: { available: false } }));
  await page.goto('/?renderProbe=1');
  await page.locator('[data-starter="1"]').click();
  const graph = JSON.parse(readFileSync('public/data/connectome.json', 'utf8')) as Graph;
  const game = createGame(1, 'johto-streaming-ui');
  game.player.team = [createMonster(game, 152, 5)];
  game.adventureVersion = 'gold'; game.dex.seen.push(152); game.dex.caught.push(152); game.versionCaught = { red: [1], gold: [152] };
  const world = new OpenWorldSimulation(graph, game, 9402);
  world.setControlMode('manual');
  const save = packSave(game, graph, { ...defaultView(), openWorld: world.snapshot(), openWorldPaused: true });
  await page.locator('#import-file').setInputFiles({ name: 'johto.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(save)) });
  await expect(page.locator('#ow-host')).toHaveAttribute('data-region', 'johto');
  await expect(page.locator('#world-biome')).toHaveText('연두마을');
  const probe = () => page.evaluate(() => (window as any).__renderProbe?.read());
  await expect.poll(async () => (await probe())?.loadedPokemon ?? [], { timeout: 45000 }).toContain(152);
  const first = await probe();
  expect(first.streaming.detailedCreatures).toBeLessThanOrEqual(8);
  expect(first.streaming.terrainChunks).toBeLessThan(36);
  expect(first.streaming.activeLoads).toBeLessThanOrEqual(3);
  expect(modelRequests.size).toBeLessThanOrEqual(10);
  expect(modelRequests.size).toBeGreaterThan(0);
  mkdirSync('artifacts/world-expansion', { recursive: true });
  await page.screenshot({ path: 'artifacts/world-expansion/johto.png' });

  await page.locator('#world-pause').click();
  await page.keyboard.down('KeyW'); await page.waitForTimeout(750); await page.keyboard.up('KeyW');
  await page.locator('#world-pause').click();
  const moved = (await probe()).streaming.player;
  expect(Math.hypot(moved.x - first.streaming.player.x, moved.z - first.streaming.player.z)).toBeGreaterThan(1);

  await page.locator('#world-map-open').click();
  await expect(page.locator('#world-region option')).toHaveCount(10);
  await page.locator('#world-region').selectOption('hoenn');
  await expect(page.locator('#world-map-region-name')).toHaveText('HOENN REGION');
  await page.locator('#world-map-close').click();
  await expect(page.locator('#ow-host')).toHaveAttribute('data-region', 'hoenn');
  await expect(page.locator('#world-version')).toHaveValue(getWorldAtlas('hoenn').defaultVersion);
  await page.locator('#save-now').click();
  await expect(page.locator('#toast')).toContainText('저장');
  await page.reload();
  await expect(page.locator('#ow-host')).toHaveAttribute('data-region', 'hoenn');
  await expect.poll(async () => (await probe())?.streaming?.region).toBe('hoenn');
  const restored = await probe();
  expect(restored.streaming.terrainChunks).toBeLessThan(36);
  await page.screenshot({ path: 'artifacts/world-expansion/hoenn.png' });

  await page.setViewportSize({ width: 390, height: 844 });
  const battle = page.locator('.world-battle-hud');
  if (await battle.getAttribute('open') !== null) await battle.locator('summary').first().click();
  await expect.poll(async () => (await probe())?.streaming?.modelLimit).toBe(4);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/world-expansion/mobile-hoenn.png' });
  expect(errors).toEqual([]);
  writeFileSync('artifacts/world-expansion/lod-browser.json', JSON.stringify({ first, restored, mobile: await probe(), modelRequests: [...modelRequests], errors }, null, 2));
});
