"""Generate local authored material palettes from the pinned front sprites.

The source sprites and source GLBs remain unchanged. The generated TypeScript is
small color data used to texture the externally hosted, untextured HOME fallback
geometry at runtime; the PNG swatches and JSON receipt are review evidence.
"""
from collections import Counter
from hashlib import sha256
from pathlib import Path
import json
from PIL import Image, ImageDraw

IDS = [850,851,852,853,854,859,860,861,863,864,866,868,873,878,879,882,883,918,919,931,935,936,938,939,940,944,950,951,952,953,954,955,956,961,963,964,968,969,970,971,972,976,977,986,988,989,991,992,993,1011,1012,1013,1022,1024]
SPRITE_COMMIT = "2ecb4eeacd5a1718621fc30f12772e3f60d830b9"
OUT = Path("artifacts/research/home-model-rigging/palettes")

def distance(a, b):
    return sum((x-y)**2 for x,y in zip(a,b)) ** .5

def palette(path: Path):
    rgba = Image.open(path).convert("RGBA")
    opaque = Image.new("RGBA", rgba.size)
    opaque.putdata([pixel if pixel[3] > 32 else (0,0,0,0) for pixel in rgba.getdata()])
    rgb = Image.new("RGB", rgba.size, "white")
    rgb.paste(opaque, mask=opaque.getchannel("A"))
    quantized = rgb.quantize(colors=12, method=Image.Quantize.MEDIANCUT).convert("RGB")
    counts = Counter(quantized.getdata())
    chosen = []
    for color, _ in counts.most_common():
        if max(color) > 247 and min(color) > 242: continue
        if min(color) < 18 and max(color) < 58: continue
        if all(distance(color, old) >= 34 for old in chosen): chosen.append(color)
        if len(chosen) == 6: break
    fallback = [(90,110,130),(210,215,220),(45,55,65),(170,90,100),(225,175,70),(80,150,120)]
    for color in fallback:
        if len(chosen) == 6: break
        if all(distance(color, old) >= 25 for old in chosen): chosen.append(color)
    return chosen[:6]

OUT.mkdir(parents=True, exist_ok=True)
rows = []
for species_id in IDS:
    sprite = Path(f"public/pokemon/{species_id}.png")
    colors = palette(sprite)
    swatch = Image.new("RGB", (384, 64))
    draw = ImageDraw.Draw(swatch)
    for index, color in enumerate(colors): draw.rectangle((index*64, 0, (index+1)*64-1, 63), fill=color)
    swatch_path = OUT / f"{species_id}.png"
    swatch.save(swatch_path, optimize=True)
    rows.append({
        "id": species_id,
        "sprite": str(sprite).replace("\\", "/"),
        "spriteSha256": sha256(sprite.read_bytes()).hexdigest(),
        "colors": ["#%02x%02x%02x" % color for color in colors],
        "swatch": str(swatch_path).replace("\\", "/"),
        "swatchSha256": sha256(swatch_path.read_bytes()).hexdigest(),
    })

ts = """// Generated by scripts/author-home-model-palettes.py. Source sprites remain unchanged.\n"""
ts += "export const HOME_AUTHORED_PALETTES: Readonly<Record<number, readonly string[]>> = "
ts += json.dumps({row["id"]: row["colors"] for row in rows}, separators=(",", ":")) + ";\n"
ts += "export const HOME_AUTHORED_PALETTE_IDS: readonly number[] = Object.keys(HOME_AUTHORED_PALETTES).map(Number);\n"
Path("src/data/pokemon-home-authored-palettes.ts").write_text(ts, encoding="utf-8")
home_manifest = json.loads(Path("src/data/pokemon-home-research-manifest.json").read_text(encoding="utf-8"))
inspections = {row["id"]: row for row in home_manifest["result"]["inspections"]}
source_rows = {row["id"]: {
    "id": row["id"], "url": row["url"], "sourcePath": row["path"], "bytes": row["bytes"],
    "sha256": inspections[row["id"]]["sha256"], "gitBlobSha1": row["gitBlobSha1"],
} for row in home_manifest["selection"]["files"]}
source_ts = "// Generated by scripts/author-home-model-palettes.py from the SHA-verified local research manifest.\n"
source_ts += f"export const HOME_MODEL_REPOSITORY = {json.dumps(home_manifest['source']['repository'])};\n"
source_ts += f"export const HOME_MODEL_COMMIT = {json.dumps(home_manifest['source']['commit'])};\n"
source_ts += "export const HOME_RUNTIME_MODEL_SOURCES: Readonly<Record<number, { id:number; url:string; sourcePath:string; bytes:number; sha256:string; gitBlobSha1:string }>> = " + json.dumps(source_rows, separators=(",", ":")) + ";\n"
source_ts += "export const HOME_RUNTIME_MODEL_IDS: readonly number[] = Object.keys(HOME_RUNTIME_MODEL_SOURCES).map(Number);\n"
Path("src/data/pokemon-home-runtime-sources.ts").write_text(source_ts, encoding="utf-8")
receipt = {
    "schema": 1,
    "method": "Six-color palettes quantized from each pinned 96x96 front sprite, excluding transparent, near-white background, near-black outline, and near-duplicate colors. Runtime makes a small authored checker texture per source material; this does not claim source texture recovery.",
    "source": {"repository": "https://github.com/PokeAPI/sprites", "commit": SPRITE_COMMIT, "paths": "sprites/pokemon/{id}.png"},
    "classification": "authored-derived-palette-local-code; source sprites and untextured GLBs unchanged",
    "scope": {"requested": len(IDS), "generated": len(rows)},
    "results": rows,
}
Path("artifacts/research/home-model-rigging/palette-verification.json").write_text(json.dumps(receipt, indent=2)+"\n", encoding="utf-8")
print(json.dumps(receipt["scope"]))
