import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { pipeline } from 'node:stream/promises';

const commit='429de1288cea0d43f5b4f56305d2276e94239d65',repository='https://github.com/Pokemon-3D-api/assets';
const treeUrl=`https://api.github.com/repos/Pokemon-3D-api/assets/git/trees/${commit}?recursive=1`,raw=`https://raw.githubusercontent.com/Pokemon-3D-api/assets/${commit}`;
const cache=resolve('data/local/pokemon-models-expanded',commit,'forms'),output=resolve('artifacts/research/region-expansion/form-model-audit.json');
type Entry={path:string;type:string;sha:string;size:number};
const digest=async(path:string,algorithm:'sha1'|'sha256',gitSize?:number)=>{const hash=createHash(algorithm);if(gitSize!==undefined)hash.update(`blob ${gitSize}\0`);for await(const chunk of createReadStream(path))hash.update(chunk as Buffer);return hash.digest('hex');};
const exists=async(path:string)=>stat(path).then(()=>true).catch(()=>false);
async function fetchEntry(entry:Entry){const name=basename(entry.path),target=resolve(cache,name),partial=`${target}.part`;await mkdir(dirname(target),{recursive:true});if(await exists(target)&&await stat(target).then(v=>v.size)===entry.size&&await digest(target,'sha1',entry.size)===entry.sha)return target;const offset=await stat(partial).then(v=>v.size).catch(()=>0);const response=await fetch(`${raw}/${entry.path}`,{headers:{'User-Agent':'choketmon-form-model-audit/1.0',...(offset?{Range:`bytes=${offset}-`}:{})}});if(!response.ok||!response.body)throw new Error(`${name}: HTTP ${response.status}`);if(offset&&response.status!==206){await rm(partial,{force:true});return fetchEntry(entry);}await pipeline(response.body as unknown as NodeJS.ReadableStream,createWriteStream(partial,{flags:offset?'a':'w'}));await rename(partial,target);if(await digest(target,'sha1',entry.size)!==entry.sha)throw new Error(`${name}: git blob mismatch`);return target;}
function inspect(bytes:Buffer){if(bytes.toString('ascii',0,4)!=='glTF'||bytes.readUInt32LE(4)!==2)throw new Error('invalid GLB');let offset=12,document:any;while(offset<bytes.length){const length=bytes.readUInt32LE(offset),type=bytes.readUInt32LE(offset+4);offset+=8;const chunk=bytes.subarray(offset,offset+length);offset+=length;if(type===0x4e4f534a)document=JSON.parse(chunk.toString('utf8').replace(/[\u0000\u0020]+$/g,''));}if(!document?.meshes?.length)throw new Error('geometry missing');return{meshes:document.meshes.length,skins:document.skins?.length??0,animations:document.animations?.length??0};}
const response=await fetch(treeUrl,{headers:{'User-Agent':'choketmon-form-model-audit/1.0'}});if(!response.ok)throw new Error(`tree HTTP ${response.status}`);const tree=await response.json() as {sha:string;truncated:boolean;tree:Entry[]};if(tree.sha!==commit||tree.truncated)throw new Error('pinned tree mismatch');
const entries=tree.tree.filter(entry=>entry.type==='blob'&&/^models\/opt\/regular\/.+\.glb$/.test(entry.path)&&!/^models\/opt\/regular\/\d+\.glb$/.test(entry.path));
const results:Array<object>=[];let cursor=0;await Promise.all(Array.from({length:6},async()=>{while(cursor<entries.length){const entry=entries[cursor++],path=await fetchEntry(entry),bytes=await readFile(path);results.push({file:basename(entry.path),sourcePath:entry.path,sourceUrl:`${raw}/${entry.path}`,bytes:bytes.length,sourceGitBlobSha1:entry.sha,sha256:createHash('sha256').update(bytes).digest('hex'),...inspect(bytes)});}}));
results.sort((a,b)=>String((a as any).file).localeCompare(String((b as any).file)));await mkdir(dirname(output),{recursive:true});await writeFile(output,JSON.stringify({schema:1,generatedAt:new Date().toISOString(),source:{repository,commit},rights:'Research cache only. Repository MIT does not establish redistribution rights for Pokemon model assets; files are excluded from deployment.',scope:{files:results.length,bytes:results.reduce((sum,row)=>sum+(row as any).bytes,0)},results},null,2)+'\n');console.log(JSON.stringify({files:results.length,bytes:results.reduce((sum,row)=>sum+(row as any).bytes,0)}));
