import { readFile, writeFile } from 'node:fs/promises';
import { parse } from 'csv-parse/sync';

const ROOT = new URL('../', import.meta.url);
const CACHE = new URL('src/data/.cache/pokeapi/', ROOT);
type Row = Record<string, string>;
const rows = async (name: string) => parse(await readFile(new URL(name, CACHE)), { columns: true, skip_empty_lines: true }) as Row[];
const groupBy = <T, K>(values: T[], key: (value: T) => K) => {
  const result = new Map<K, T[]>();
  for (const value of values) result.set(key(value), [...(result.get(key(value)) ?? []), value]);
  return result;
};

const manifest = JSON.parse(await readFile(new URL('src/data/source-manifest.json', ROOT), 'utf8')) as { resolvedCommit: string };
const [forms, pokemon, statRows, statNames, typeRows, typeNames, abilityRows, abilities, abilityNames, moveRows, versionGroups] = await Promise.all([
  rows('pokemon_forms.csv'), rows('pokemon.csv'), rows('pokemon_stats.csv'), rows('stats.csv'), rows('pokemon_types.csv'), rows('types.csv'),
  rows('pokemon_abilities.csv'), rows('abilities.csv'), rows('ability_names.csv'), rows('pokemon_moves.csv'), rows('version_groups.csv'),
]);
const pokemonById = new Map(pokemon.map(row => [Number(row.id), row]));
const defaultBySpecies = new Map(pokemon.filter(row => row.is_default === '1').map(row => [Number(row.species_id), Number(row.id)]));
const statsByPokemon = groupBy(statRows, row => Number(row.pokemon_id));
const statById = new Map(statNames.map(row => [Number(row.id), row.identifier]));
const typesByPokemon = groupBy(typeRows, row => Number(row.pokemon_id));
const typeById = new Map(typeNames.map(row => [Number(row.id), row.identifier]));
const abilitiesByPokemon = groupBy(abilityRows, row => Number(row.pokemon_id));
const abilityById = new Map(abilities.map(row => [Number(row.id), row.identifier]));
const koreanAbilities = new Map(abilityNames.filter(row => row.local_language_id === '3').map(row => [Number(row.ability_id), row.name]));
const englishAbilities = new Map(abilityNames.filter(row => row.local_language_id === '9').map(row => [Number(row.ability_id), row.name]));
const moveGroups = groupBy(moveRows.filter(row => row.pokemon_move_method_id === '1'), row => Number(row.pokemon_id));
const groupOrder = new Map(versionGroups.map(row => [Number(row.id), Number(row.order)]));

const selectedMoves = (pokemonId: number, speciesId: number) => {
  const source = moveGroups.get(pokemonId)?.length ? pokemonId : defaultBySpecies.get(speciesId)!;
  const available = moveGroups.get(source) ?? [];
  const versionGroupId = [...new Set(available.map(row => Number(row.version_group_id)))]
    .sort((a, b) => (groupOrder.get(b) ?? 0) - (groupOrder.get(a) ?? 0))[0];
  return available.filter(row => Number(row.version_group_id) === versionGroupId)
    .map(row => ({ level: Number(row.level), moveId: Number(row.move_id), order: Number(row.order || 0) }))
    .sort((a, b) => a.level - b.level || a.order - b.order || a.moveId - b.moveId)
    .filter((entry, index, all) => !all.slice(0, index).some(item => item.level === entry.level && item.moveId === entry.moveId))
    .map(({ level, moveId }) => ({ level, moveId }));
};

const records = forms.filter(row => row.form_identifier === 'alola' || row.is_mega === '1').map(form => {
  const pokemonId = Number(form.pokemon_id), pokemonRow = pokemonById.get(pokemonId)!;
  const speciesId = Number(pokemonRow.species_id);
  const statValues = Object.fromEntries((statsByPokemon.get(pokemonId) ?? []).map(row => [statById.get(Number(row.stat_id)), Number(row.base_stat)]));
  return {
    formId: Number(form.id), pokemonId, speciesId, identifier: form.identifier, kind: form.is_mega === '1' ? 'mega' : 'alola',
    types: (typesByPokemon.get(pokemonId) ?? []).sort((a, b) => Number(a.slot) - Number(b.slot)).map(row => typeById.get(Number(row.type_id))),
    baseStats: { hp: statValues.hp, attack: statValues.attack, defense: statValues.defense,
      specialAttack: statValues['special-attack'], specialDefense: statValues['special-defense'], speed: statValues.speed },
    abilities: (abilitiesByPokemon.get(pokemonId) ?? []).sort((a, b) => Number(a.slot) - Number(b.slot)).map(row => {
      const id = Number(row.ability_id); return { id, slot: Number(row.slot), hidden: row.is_hidden === '1', slug: abilityById.get(id),
        name: koreanAbilities.get(id) ?? englishAbilities.get(id) ?? abilityById.get(id), englishName: englishAbilities.get(id) ?? abilityById.get(id) };
    }),
    levelUpMoves: selectedMoves(pokemonId, speciesId),
  };
}).sort((a, b) => a.speciesId - b.speciesId || a.formId - b.formId);

const output = `// Generated by scripts/generate-pokemon-combat-forms.ts from pinned PokeAPI commit ${manifest.resolvedCommit}. Do not edit by hand.\n`
  + `import type { BaseStats, PokemonType } from '../game/contracts.ts';\n`
  + `import { POKEMON_FORMS } from './pokemon-versions.ts';\n`
  + `import type { SourceAbility } from './pokemon-abilities.generated.ts';\n\n`
  + `type CombatFormRecord = { formId: number; pokemonId: number; speciesId: number; identifier: string; kind: 'alola' | 'mega'; types: PokemonType[]; baseStats: BaseStats; abilities: SourceAbility[]; levelUpMoves: { level: number; moveId: number }[] };\n`
  + `export type PokemonCombatFormProfile = CombatFormRecord & { name: string; frontSprite: string | null; backSprite: string | null };\n`
  + `const RECORDS: CombatFormRecord[] = ${JSON.stringify(records)};\n`
  + `const metadata = new Map(POKEMON_FORMS.map(form => [form.identifier, form]));\n`
  + `export const COMBAT_FORMS: readonly PokemonCombatFormProfile[] = RECORDS.map(record => { const form = metadata.get(record.identifier); if (!form) throw new Error(\`Missing form metadata: \${record.identifier}\`); return { ...record, name: form.name, frontSprite: form.frontSprite, backSprite: form.backSprite }; });\n`
  + `const byIdentifier = new Map(COMBAT_FORMS.map(form => [form.identifier, form]));\n`
  + `const alolaBySpecies = new Map(COMBAT_FORMS.filter(form => form.kind === 'alola').map(form => [form.speciesId, form]));\n`
  + `const megaBySpecies = new Map<number, PokemonCombatFormProfile[]>(); for (const form of COMBAT_FORMS.filter(form => form.kind === 'mega')) megaBySpecies.set(form.speciesId, [...(megaBySpecies.get(form.speciesId) ?? []), form]);\n`
  + `export function getCombatForm(identifier: string): PokemonCombatFormProfile | undefined { return byIdentifier.get(identifier); }\n`
  + `export function getAlolaCombatForm(speciesId: number): PokemonCombatFormProfile | undefined { return alolaBySpecies.get(speciesId); }\n`
  + `export function getMegaCombatForms(speciesId: number): readonly PokemonCombatFormProfile[] { return megaBySpecies.get(speciesId) ?? []; }\n`
  + `export function getMegaCombatForm(speciesId: number, identifier?: string): PokemonCombatFormProfile | undefined { const forms = getMegaCombatForms(speciesId); return identifier ? forms.find(form => form.identifier === identifier) : forms[0]; }\n`
  + `export function isMegaEligible(speciesId: number): boolean { return megaBySpecies.has(speciesId); }\n`;
await writeFile(new URL('src/data/pokemon-combat-forms.ts', ROOT), output);
await writeFile(new URL('rust-server/data/pokemon-combat-forms.json', ROOT), JSON.stringify({
  sourceCommit: manifest.resolvedCommit,
  forms: records.map(({ identifier, speciesId, kind, types, baseStats, abilities, levelUpMoves }) => ({ identifier, speciesId, kind, types, baseStats, abilities, levelUpMoves })),
}));
