import { readFileSync, writeFileSync } from 'node:fs';

/** Writes src/data/pokemon-body-shapes.ts from the pinned PokeAPI species table (`shape_id`, the Pokédex body icon). */
const SHAPES = ['ball', 'squiggle', 'fish', 'arms', 'blob', 'upright', 'legs', 'quadruped', 'wings', 'tentacles', 'heads', 'humanoid', 'bug-wings', 'armor'] as const;
const lines = readFileSync(new URL('../src/data/.cache/pokeapi/pokemon_species.csv', import.meta.url), 'utf8').trim().split(/\r?\n/);
const header = lines[0].split(','), idColumn = header.indexOf('id'), shapeColumn = header.indexOf('shape_id');
const shapes = new Map(lines.slice(1).map(line => { const row = line.split(','); return [Number(row[idColumn]), Number(row[shapeColumn])]; }));
let codes = '';
for (let id = 1; id <= 1025; id++) {
  const shape = shapes.get(id);
  if (!shape || shape < 1 || shape > SHAPES.length) throw new Error(`Species ${id} has no body shape`);
  codes += String.fromCharCode(96 + shape);
}
const lines80 = codes.match(/.{1,100}/g)!.map(chunk => `  '${chunk}'`).join(' +\n');
writeFileSync(new URL('../src/data/pokemon-body-shapes.ts', import.meta.url), `// Generated by scripts/generate-body-shapes.ts from the pinned PokeAPI pokemon_species.csv (shape_id).
/** The Pokédex body icon of each species, as PokeAPI names it. */
export type PokemonBodyShape = ${SHAPES.map(shape => `'${shape}'`).join(' | ')};
const SHAPES: readonly PokemonBodyShape[] = [${SHAPES.map(shape => `'${shape}'`).join(', ')}];
/** One letter per species 1..1025: a = ${SHAPES[0]} (shape id 1) … n = ${SHAPES[13]} (shape id 14). */
const CODES =
${lines80};

export function pokemonBodyShape(speciesId: number): PokemonBodyShape | undefined {
  if (!Number.isInteger(speciesId) || speciesId < 1 || speciesId > CODES.length) return undefined;
  return SHAPES[CODES.charCodeAt(speciesId - 1) - 97];
}
`);
console.log('wrote src/data/pokemon-body-shapes.ts', codes.length);
