import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { parse } from 'csv-parse/sync';

const ROOT = new URL('../', import.meta.url);
const CACHE = new URL('src/data/.cache/pokeapi/', ROOT);
const OUTPUT = new URL('src/data/pokemon-abilities.generated.ts', ROOT);
const VALIDATION_OUTPUT = new URL('rust-server/data/pokemon-abilities-validation.json', ROOT);
const MANIFEST = new URL('src/data/source-manifest.json', ROOT);
const FILES = ['abilities.csv', 'ability_names.csv', 'ability_prose.csv', 'pokemon.csv', 'pokemon_abilities.csv'] as const;
type Row = Record<string, string>;
const rows = (bytes: Buffer) => parse(bytes, { columns: true, skip_empty_lines: true }) as Row[];
const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');

const manifest = JSON.parse(await readFile(MANIFEST, 'utf8')) as {
  resolvedCommit: string;
  csvFiles: Array<{ file: string; url: string; sha256: string; bytes: number }>;
};
if (!/^[a-f0-9]{40}$/.test(manifest.resolvedCommit)) throw new Error('Pinned PokeAPI commit required.');
const buffers = new Map(await Promise.all(FILES.map(async file => [file, await readFile(new URL(file, CACHE))] as const)));
const tables = new Map([...buffers].filter(([file]) => file !== 'ability_prose.csv').map(([file, bytes]) => [file, rows(bytes)]));
const abilities = new Map(tables.get('abilities.csv')!.map(row => [Number(row.id), row]));
const names = tables.get('ability_names.csv')!;
const localized = (language: number) => new Map(names.filter(row => Number(row.local_language_id) === language)
  .map(row => [Number(row.ability_id), row.name]));
const ko = localized(3), en = localized(9);
const defaultPokemonBySpecies = new Map(tables.get('pokemon.csv')!.filter(row => row.is_default === '1')
  .map(row => [Number(row.species_id), Number(row.id)]));
const slotsByPokemon = new Map<number, Row[]>();
for (const row of tables.get('pokemon_abilities.csv')!) {
  const pokemonId = Number(row.pokemon_id);
  slotsByPokemon.set(pokemonId, [...(slotsByPokemon.get(pokemonId) ?? []), row]);
}
const speciesAbilities = Object.fromEntries([...defaultPokemonBySpecies].sort(([a], [b]) => a - b).map(([speciesId, pokemonId]) => {
  const slots = (slotsByPokemon.get(pokemonId) ?? []).sort((a, b) => Number(a.slot) - Number(b.slot)).map(row => {
    const id = Number(row.ability_id), source = abilities.get(id);
    if (!source) throw new Error(`Missing ability ${id}`);
    return { id, slot: Number(row.slot), hidden: row.is_hidden === '1', slug: source.identifier,
      name: ko.get(id) ?? en.get(id) ?? source.identifier, englishName: en.get(id) ?? source.identifier };
  });
  if (!slots.length) throw new Error(`Missing abilities for species ${speciesId}`);
  return [speciesId, slots];
}));
const sourceFiles = [...buffers].map(([file, bytes]) => ({ file,
  url: `https://raw.githubusercontent.com/PokeAPI/pokeapi/${manifest.resolvedCommit}/data/v2/csv/${file}`,
  sha256: sha256(bytes), bytes: bytes.length }));
const output = `// Generated by scripts/generate-pokemon-abilities.ts. Do not edit by hand.\n` +
  `export type SourceAbility = { id: number; slot: number; hidden: boolean; slug: string; name: string; englishName: string };\n` +
  `export const POKEMON_ABILITY_SOURCE = ${JSON.stringify({ dataset: 'PokeAPI CSV', resolvedCommit: manifest.resolvedCommit, files: sourceFiles }, null, 2)} as const;\n` +
  `export const SPECIES_ABILITIES: Readonly<Record<number, readonly SourceAbility[]>> = ${JSON.stringify(speciesAbilities)};\n`;
await writeFile(OUTPUT, output);
await writeFile(VALIDATION_OUTPUT, JSON.stringify(speciesAbilities));

const existing = new Map(manifest.csvFiles.map(entry => [entry.file, entry]));
for (const entry of sourceFiles) existing.set(entry.file, entry);
manifest.csvFiles = [...existing.values()].sort((a, b) => a.file.localeCompare(b.file));
await writeFile(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Wrote ${Object.keys(speciesAbilities).length} species ability records from ${manifest.resolvedCommit}.`);
