import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse } from 'csv-parse/sync';

type SpeciesRow = { id: string; gender_rate: string; hatch_counter: string };
type EggGroupRow = { species_id: string; egg_group_id: string };

const root = resolve(import.meta.dirname, '..');
const cache = resolve(root, 'src/data/.cache/pokeapi');
const eggGroupPath = resolve(cache, 'pokemon_egg_groups.csv');
if (!existsSync(eggGroupPath)) {
  const response = await fetch('https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_egg_groups.csv');
  if (!response.ok) throw new Error(`Could not download PokeAPI egg groups: ${response.status}`);
  writeFileSync(eggGroupPath, await response.text());
}
const speciesRows = parse(readFileSync(resolve(cache, 'pokemon_species.csv'), 'utf8'), { columns: true, skip_empty_lines: true }) as SpeciesRow[];
const eggGroupRows = parse(readFileSync(eggGroupPath, 'utf8'), { columns: true, skip_empty_lines: true }) as EggGroupRow[];
const groups = new Map<number, number[]>();
for (const row of eggGroupRows) {
  const id = Number(row.species_id);
  if (id <= 1025) groups.set(id, [...(groups.get(id) ?? []), Number(row.egg_group_id)]);
}
const rows = speciesRows.filter(row => Number(row.id) <= 1025).map(row => ({
  id: Number(row.id), genderRate: Number(row.gender_rate), hatchCounter: Number(row.hatch_counter), eggGroups: groups.get(Number(row.id)) ?? [],
}));
if (rows.length !== 1025 || rows.some(row => !row.eggGroups.length)) throw new Error(`Incomplete breeding data: ${rows.length} species`);
const source = `// Generated by scripts/generate-breeding-data.ts from PokeAPI CSV data. Do not edit by hand.\n`+
  `// Sources: https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species.csv\n`+
  `//          https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_egg_groups.csv\n`+
  `export type BreedingSpeciesData = { genderRate: number; hatchCounter: number; eggGroups: readonly number[] };\n`+
  `export const BREEDING_SPECIES: Readonly<Record<number, BreedingSpeciesData>> = ${JSON.stringify(Object.fromEntries(rows.map(({ id, ...data }) => [id, data])))};\n`+
  `export const BREEDING_DATA_SOURCE = 'PokeAPI master CSV snapshot 2026-09-16';\n`;
writeFileSync(resolve(root, 'src/data/breeding.generated.ts'), source);
