import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'csv-parse/sync';

type Row = Record<string, string>;
const root = join('data', 'local', 'johto-gold-source');
const revision = readdirSync(root, { withFileTypes: true }).find(entry => entry.isDirectory())?.name;
if (!revision) throw new Error('Pinned PokeAPI CSV cache is missing');
const dir = join(root, revision);
const rows = (name: string): Row[] => parse(readFileSync(join(dir, name)), { columns: true, skip_empty_lines: true });
const numbers = (row: Row, ...keys: string[]) => keys.map(key => Number(row[key]));

const versions = new Map(rows('versions.csv').map(row => [row.identifier, numbers(row, 'id', 'version_group_id')]));
const slots = new Map(rows('encounter_slots.csv').map(row => [Number(row.id), { group: Number(row.version_group_id), method: Number(row.encounter_method_id), weight: Number(row.rarity) }]));
const areas = new Map(rows('location_areas.csv').map(row => [Number(row.id), { location: Number(row.location_id), name: row.identifier }]));
const locations = new Map(rows('locations.csv').map(row => [Number(row.id), { region: Number(row.region_id), name: row.identifier }]));
const conditionValues = new Map(rows('encounter_condition_values.csv').map(row => [Number(row.id), { condition: Number(row.encounter_condition_id), name: row.identifier, isDefault: row.is_default === '1' }]));
const conditionMap = new Map<number, number[]>();
for (const row of rows('encounter_condition_value_map.csv')) {
  const [encounter, value] = numbers(row, 'encounter_id', 'encounter_condition_value_id');
  const list = conditionMap.get(encounter) ?? []; list.push(value); conditionMap.set(encounter, list);
}

type Period = 'morning' | 'day' | 'night';
type Slot = { speciesId: number; minLevel: number; maxLevel: number; weight: number };
type Pool = { locationId: string; areaId: number; areaName: string; method: string; period: Period; slots: Slot[] };
const METHOD_NAMES = new Map(rows('encounter_methods.csv').map(row => [Number(row.id), row.identifier]));
const specs = [{ region: 'kanto', regionId: 1, version: 'red' }, { region: 'johto', regionId: 2, version: 'crystal' }] as const;
const output: Record<string, Pool[]> = {};
for (const spec of specs) {
  const [versionId, groupId] = versions.get(spec.version)!;
  const grouped = new Map<string, Pool>();
  for (const row of rows('encounters.csv')) {
    if (Number(row.version_id) !== versionId) continue;
    const areaId = Number(row.location_area_id), area = areas.get(areaId), location = area && locations.get(area.location);
    const slot = slots.get(Number(row.encounter_slot_id));
    if (!area || !location || location.region !== spec.regionId || !slot || slot.group !== groupId) continue;
    const conditions = (conditionMap.get(Number(row.id)) ?? []).map(id => conditionValues.get(id)!).filter(Boolean);
    if (conditions.some(value => value.condition !== 2 && !value.isDefault)) continue;
    const explicit = conditions.find(value => value.condition === 2)?.name;
    const periods: Period[] = spec.region === 'kanto' ? ['morning', 'day', 'night']
      : explicit === 'time-morning' ? ['morning'] : explicit === 'time-night' ? ['night'] : explicit === 'time-day' ? ['day'] : ['morning', 'day', 'night'];
    for (const period of periods) {
      const method = METHOD_NAMES.get(slot.method) ?? `method-${slot.method}`;
      const key = `${location.name}|${areaId}|${method}|${period}`;
      let pool = grouped.get(key);
      if (!pool) { pool = { locationId: location.name, areaId, areaName: area.name, method, period, slots: [] }; grouped.set(key, pool); }
      pool.slots.push({ speciesId: Number(row.pokemon_id), minLevel: Number(row.min_level), maxLevel: Number(row.max_level), weight: slot.weight });
    }
  }
  output[spec.region] = [...grouped.values()].sort((a, b) => a.locationId.localeCompare(b.locationId) || a.areaId - b.areaId || a.period.localeCompare(b.period));
}
const sourceFiles = ['encounters.csv', 'encounter_slots.csv', 'encounter_condition_values.csv', 'encounter_condition_value_map.csv', 'location_areas.csv', 'locations.csv', 'versions.csv'];
const checksums = Object.fromEntries(sourceFiles.map(name => [name, createHash('sha256').update(readFileSync(join(dir, name))).digest('hex')]));
const text = `// Generated by scripts/generate-regional-encounters.ts from the pinned PokeAPI CSV cache.\n`
  + `export type RegionalEncounterSlot = { speciesId: number; minLevel: number; maxLevel: number; weight: number };\n`
  + `export type RegionalEncounterPool = { locationId: string; areaId: number; areaName: string; method: string; period: 'morning' | 'day' | 'night'; slots: RegionalEncounterSlot[] };\n`
  + `export const REGIONAL_ENCOUNTER_SOURCE = ${JSON.stringify({ repository: 'https://github.com/PokeAPI/pokeapi', revision, license: 'BSD-3-Clause', versions: { kanto: 'firered', johto: 'heartgold' }, checksums })} as const;\n`
  + `export const REGIONAL_ENCOUNTER_POOLS: Record<'kanto' | 'johto', RegionalEncounterPool[]> = ${JSON.stringify(output)};\n`;
writeFileSync(join('src', 'data', 'regional-encounters.generated.ts'), text);
console.log(Object.fromEntries(Object.entries(output).map(([region, pools]) => [region, { pools: pools.length, species: new Set(pools.flatMap(pool => pool.slots.map(slot => slot.speciesId))).size }])));
