#!/usr/bin/env python3
"""Build the single-request Choket Sans UI subset from official Pretendard 1.3.9."""

from __future__ import annotations

import hashlib
import re
import tempfile
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE_URL = "https://raw.githubusercontent.com/orioncactus/pretendard/v1.3.9/packages/pretendard/dist/web/variable/woff2/PretendardVariable.woff2"
SOURCE_SHA256 = "9599f12fd42fc0bce1cd50b47a0c022e108d7aa64dd0d1bb0ed44f3282d900b4"
OUTPUT = ROOT / "public/fonts/ChoketSansVariable.woff2"
CSS_OUTPUT = ROOT / "src/ui/fonts.css"
TEXT_EXTENSIONS = {".ts", ".tsx", ".css", ".html", ".json"}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_text() -> str:
    paths = [ROOT / "index.html"]
    paths.extend(path for path in (ROOT / "src").rglob("*") if path.is_file() and path.suffix in TEXT_EXTENSIONS)
    return "".join(path.read_text(encoding="utf-8", errors="ignore") for path in paths)


def unicode_ranges(codepoints: set[int]) -> str:
    ranges: list[tuple[int, int]] = []
    for point in sorted(codepoints):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], point)
        else:
            ranges.append((point, point))
    return ", ".join(f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}" for start, end in ranges)


def rename(font: TTFont) -> None:
    replacements = {
        1: "Choket Sans", 2: "Regular", 3: "Choket Sans Variable 1.3.9",
        4: "Choket Sans Variable", 6: "ChoketSansVariable", 16: "Choket Sans", 17: "Regular",
        21: "Choket Sans", 22: "Regular",
    }
    for record in font["name"].names:
        replacement = replacements.get(record.nameID)
        if replacement is None:
            continue
        try:
            record.string = replacement.encode(record.getEncoding())
        except (LookupError, UnicodeEncodeError):
            record.string = replacement.encode("utf-16-be")


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    bundled_source = ROOT / "public/fonts/PretendardVariable.woff2"
    with tempfile.TemporaryDirectory(prefix="choket-font-") as temporary:
        source = bundled_source if bundled_source.exists() else Path(temporary) / "PretendardVariable.woff2"
        if not source.exists():
            urllib.request.urlretrieve(SOURCE_URL, source)
        if digest(source) != SOURCE_SHA256:
            raise RuntimeError("Pretendard source checksum mismatch")

        requested = set(range(0x20, 0x7F)) | {ord(character) for character in source_text() if not character.isspace()}
        font = TTFont(source, recalcTimestamp=False)
        font.recalcTimestamp = False
        available = set(font.getBestCmap())
        codepoints = requested & available
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = ["*"]
        options.name_legacy = True
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=codepoints)
        subsetter.subset(font)
        rename(font)
        font.save(OUTPUT)

    css = f"""/* Generated by scripts/subset-ui-font.py from official Pretendard 1.3.9. */
@font-face {{
  font-family: 'Choket Sans';
  src: url('/fonts/ChoketSansVariable.woff2') format('woff2-variations');
  font-style: normal;
  font-weight: 45 930;
  font-display: swap;
  unicode-range: {unicode_ranges(codepoints)};
}}

:root {{
  --ui-font-family: 'Choket Sans', -apple-system, BlinkMacSystemFont, system-ui, 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', sans-serif;
  font-family: var(--ui-font-family);
}}

button,
input,
select,
textarea {{ font-family: inherit; }}
"""
    CSS_OUTPUT.write_text(css, encoding="utf-8", newline="\n")
    print(f"source={SOURCE_SHA256} glyphs={len(codepoints)} bytes={OUTPUT.stat().st_size} sha256={digest(OUTPUT)}")


if __name__ == "__main__":
    main()
