import { chromium } from '@playwright/test';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { HOME_RUNTIME_MODEL_IDS } from '../src/data/pokemon-home-runtime-sources';
import { getPokemonModelSource, hasPokemonModel } from '../src/data/pokemon-models';

const localManifest=JSON.parse(readFileSync('src/data/pokemon-home-research-manifest.json','utf8')) as {result:{inspections:Array<{id:number;localPath:string;sha256:string}>}};
const localById=new Map(localManifest.result.inspections.map(row=>[row.id,row]));
const catalog=HOME_RUNTIME_MODEL_IDS.map(id=>{const source=getPokemonModelSource(id),local=localById.get(id);if(!source||!local)throw new Error(`${id}: missing runtime or local source`);const digest=createHash('sha256').update(readFileSync(local.localPath)).digest('hex');return{id,url:source.url,sourcePath:source.sourcePath,sourceClass:source.sourceClass,rightsStatus:source.rightsStatus,localSha256:digest,expectedSha256:local.sha256,passed:source.sourceClass==='research-fallback'&&source.rightsStatus==='source-license-unverified'&&digest===local.sha256};});
const allNationalIds=Array.from({length:1025},(_,index)=>index+1),catalogMissing=allNationalIds.filter(id=>!hasPokemonModel(id));
const browser=await chromium.launch({headless:true}),page=await browser.newPage();await page.goto('http://127.0.0.1:5173/data/connectome.json');
const representative=[] as unknown[];
try{for(const id of [852,936,1024])representative.push(await page.evaluate(async speciesId=>{const dataPath='/src/data/pokemon-models.ts',loaderPath='/src/three/gltf-loader.ts';const [{getPokemonModelSource},{createGLTFLoader}]=await Promise.all([import(/* @vite-ignore */ dataPath),import(/* @vite-ignore */ loaderPath)]);const source=getPokemonModelSource(speciesId);if(!source)throw new Error(`${speciesId}: no source`);const asset=await createGLTFLoader().loadAsync(source.url);let meshes=0,uvMeshes=0;asset.scene.traverse((object:{isMesh?:boolean;geometry?:{getAttribute(name:string):unknown}})=>{if(object.isMesh){meshes++;if(object.geometry?.getAttribute('uv'))uvMeshes++;}});return{id:speciesId,url:source.url,meshes,uvMeshes,appearance:asset.scene.userData.authoredAppearance,rig:asset.scene.userData.authoredRig};},id));}finally{await browser.close();}
const failed=catalog.filter(row=>!row.passed),representativeFailed=representative.filter(row=>{const value=row as {appearance?:{materials?:number;uvMeshes?:number};rig?:{version?:string}};return!value.appearance?.materials||!value.appearance.uvMeshes||value.rig?.version!=='regional-authored-v4';});
const receipt={schema:1,generatedAt:new Date().toISOString(),method:'Validate all 1025 National Dex IDs resolve in the runtime catalog; compare every HOME fallback local cache byte stream to its recorded SHA-256; then load three representatives through production getPokemonModelSource + GLTFLoader from the pinned external URLs in Chromium and require authored materials, UV textures, and v4 rig metadata.',scope:{nationalIds:1025,catalogMissing,homeFallbacks:catalog.length,homeFailed:failed.map(row=>row.id),representativeFailed:representativeFailed.map(row=>(row as {id:number}).id)},catalog,representative};
writeFileSync('artifacts/research/home-model-rigging/runtime-catalog-verification.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt.scope));if(catalogMissing.length||failed.length||representativeFailed.length)process.exitCode=1;
