// Generated by scripts/generate-body-shapes.ts from the pinned PokeAPI pokemon_species.csv (shape_id).
/** The Pokédex body icon of each species, as PokeAPI names it. */
export type PokemonBodyShape = 'ball' | 'squiggle' | 'fish' | 'arms' | 'blob' | 'upright' | 'legs' | 'quadruped' | 'wings' | 'tentacles' | 'heads' | 'humanoid' | 'bug-wings' | 'armor';
const SHAPES: readonly PokemonBodyShape[] = ['ball', 'squiggle', 'fish', 'arms', 'blob', 'upright', 'legs', 'quadruped', 'wings', 'tentacles', 'heads', 'humanoid', 'bug-wings', 'armor'];
/** One letter per species 1..1025: a = ball (shape id 1) … n = armor (shape id 14). */
const CODES =
  'hhhffffffnbmnbmiiihhiibbhfffhhfhhfffhhlliigllnnlmekhhffffhhgllfflfllleejjdllhhhfdkiggccddaaadfbllnna' +
  'akgffllfakhffgfeecceelmlfflhcbcahhhhgjjnfiliiibbfffhhhlhhfffhhiiiinnmcchfllliihfflffllffffalmgfhhifa' +
  'aehaabiblfcmnlfffbbhhncjiiihhehhghflfllfflhhhfbfiilfffgffhffhhhhnamamnllglliiiilllnmgfhflnmefffllglh' +
  'hllhhfllhhfffllddcccchhhdffnmilliifbaaccnnddeenfcbafafdlhdhflacchabbcclhhedkllliicfbllhhhffflffiiihf' +
  'lmhhhllffhheemkmhhhkgbbfddffaihhlhhadgllieffflffhhnnlljccifffdlflffimhhihdlkddafffhfhljbdllhhlffbhff' +
  'ffhhfhhhhhffffffhliiihhgjjiiflflllcflllndlnanaleechhflhennffidehfiillhfhhlllaadiieekhhhldddjjcnnajkk' +
  'kcccfleddffffhaadcfffllllhiiiifnhhfnmhhhddifdfhllfffhffhllffiiinemhhdddhhflhffekedlgljekkeenbffffhhh' +
  'lfabbfadjaehhiihibddhiiihhfccciiihhnbnnninmhhcejhhgnflelhhhfgllalfjlbbbhhalffbcbehffddddaahijjlfllfd' +
  'llfihllalfflfffhffffiiinnihheehhhhhhaglbihbbiccffjjjjaaglelllffdileaekjbmgfflhhffgcfbdfhhiflfllhhlhm' +
  'hcfcdhffffhfffhhnnnlhffkkhhglliahllllaliihhhfaagjnffnngfllleeiccgghbaahhiffccclhhblhfhihhhflfmffffel' +
  'bhhchlfhfhkaaflilfkhhhhha';

export function pokemonBodyShape(speciesId: number): PokemonBodyShape | undefined {
  if (!Number.isInteger(speciesId) || speciesId < 1 || speciesId > CODES.length) return undefined;
  return SHAPES[CODES.charCodeAt(speciesId - 1) - 97];
}
